# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E2DADD
background         #111415
cursor             #9B959F

active_tab_foreground     #111415
active_tab_background     #E2DADD
inactive_tab_foreground   #E2DADD
inactive_tab_background   #111415

active_border_color   #E2DADD
inactive_border_color #111415
bell_border_color     #432C38

color0      #393B3D
color1		#432C38
color2		#403D49
color3		#3A5562
color4		#395864
color5		#8D414A
color6		#806F76
color7		#CDC1C6
color8		#8F878A
color9		#5A3B4B
color10		#555161
color11		#4D7182
color12		#4C7586
color13		#BC5762
color14		#AB949D
color15		#CDC1C6
