# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(111415)
$foreground = rgb(E2DADD)
$color0 = rgb(393B3D)
$color1 = rgb(432C38)
$color2 = rgb(403D49)
$color3 = rgb(3A5562)
$color4 = rgb(395864)
$color5 = rgb(8D414A)
$color6 = rgb(806F76)
$color7 = rgb(CDC1C6)
$color8 = rgb(8F878A)
$color9 = rgb(5A3B4B)
$color10 = rgb(555161)
$color11 = rgb(4D7182)
$color12 = rgb(4C7586)
$color13 = rgb(BC5762)
$color14 = rgb(AB949D)
$color15 = rgb(CDC1C6)
